# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2016-07-21 08:02
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=uuid.uuid4, unique=True),
        ),
    ]
